### ISSUE TITLE
[Question] Support in server side

### ISSUE THREAD

**Issue by Applelo** [dulnan/nuxt-graphql-middleware#15]
Hi, I need to do some request in server side, via custom api route. Is it possible currently ? I don't want to do a request to`/api/graphql_middleware/query/myRequest` in server side and call directly the graphql API.

Note: Thanks for your module, it makes my current project really clean :)

**Comment by dulnan** [comment]
Hey sorry for the late reply. I hope you were able to get it working in the meantime. If not (and for future reference for others), the composable can be used in server contexts by importing it from here:

```typescript
import { useGraphqlQuery } from '#graphql-composable'
```

It's important to import this one, because it behaves slightly different than the auto-imported composable available in Vue context.
